# .travis.yml
language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

cache:
  directories:
    - $HOME/.composer/cache/files

install: composer install --dev

after_script:
  - php vendor/bin/codacycoverage clover
